### ISSUE TITLE
Review Submission

### ISSUE THREAD

**Issue by not-xygen** [Wiraproject/Bootcamp-Final-Project#1]
### Halo Wiranto,

Halo ada beberapa yang harus direvisi yah:

1. Struktur HTML masih kurang tepat, harusnya begini yah:
```html
<header></header>
<main>
 <div id="content">
  <section>...</section>
  <section>...</section>
  ....
 </div>
 <aside>...</aside>
</main>
<footer></footer>
```
2. elemen `nav` bisa dipindah kedalam header yah
3. Saat ini `article`mu terbagi dalam `section` masing-masing, kamu bisa gabung article-article yang terpisah menjadi cukup 1 section yah
4 elemen `script` bisa dipindahkan ke sebelum tag penutup `body`

itu saja dari aku, mungkin bisa direvisi dan diupload ulang di repository yang sama yah. Jangan lupa kalau sudah komen dibawah dan Terimakasih

**Comment by Wiraproject** [comment]
Terima kasih kak, telah mengecek dan merevisi pekerjaan saya, maaf kak sebelumnya bila saya masih kurang tepat dalam pekerjaan saya. ini saya sudah selesai merevisi kak, mohon di koreksi lagi kak jikalau ada kesalahan, terima kasih kak...
Wiranto - 11221030 - https://github.com/Wiraproject/FinalProject.git

**Comment by not-xygen** [comment]
### Halo Wiranto,

kodemu sudah tepat, tapi masih ada beberapa yang salah seperti, kamu belum mengabungkan artikel-artikel menjadi satu `section`. jadi kamu bisa mengabungk 2 elemen `article` tersebut di satu `section` yah. Untuk sekarang kuapprove dan goodluck untuk CSS nya nanti!!

**Comment by Wiraproject** [comment]
Baik kak terimakasih, apa perlu saya upload ulang kak?

**Comment by not-xygen** [comment]
silahkan, tidak papa
